<?xml version="1.0"?>
<robot name="wheel_leg_initial_pose" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 包含宏定义 -->
  <xacro:include filename="$(find balance_bot)/urdf/leg_initial_pose_module.xacro" />

  <!-- 定义机器人参数 -->
  <xacro:property name="body_length" value="0.4" />
  <xacro:property name="body_width" value="0.3" />
  <xacro:property name="body_height" value="0.15" />

  <!-- 机器人主体 -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.02"/>
    </inertial>
  </link>

  <!-- 添加左侧腿 -->
  <xacro:leg_initial_pose_module
    prefix="left"
    parent="base_link"
    x="${0}"
    y="${body_width/2}"
    z="0"
    mirror="false" />

  <!-- 添加右侧腿 -->
  <xacro:leg_initial_pose_module
    prefix="right"
    parent="base_link"
    x="${0}"
    y="${-body_width/2}"
    z="0"
    mirror="true" />

  <!-- Gazebo插件 -->
  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Gazebo ROS控制插件 -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/wheel_leg_initial_pose</robotNamespace>
    </plugin>
  </gazebo>

</robot>